### PR TITLE
Add editor config

### LINKED ISSUE #21: use prettier as code formatter
To format all code in a consistent way through all the project and for all contributors solution like prettier is welcome !

@sallesma I let you review the result and fix format rule according to your preference/habits.

### PR DESCRIPTION
**Pull request by mmouterde**
fix #21

### CODE REVIEW

**Comment by sallesma** [comment]
I think I would go for the same rules as in the discin codebase : https://github.com/disc-in/UltimateApp/blob/master/.prettierrc

I am also wondering whether we should also use other tools such as eslint, lint-staged and so on to enforce all these rules

what do you think?

**Comment by mmouterde** [comment]
- ok for same rules as discin.
- I think eslint is a must have, but no idea if this works well with reactNative ?!
- I usually not use lint-staged as my CI ensure linting, as you want

**Comment by mmouterde** [comment]
- ok for same rules as discin.
- I think eslint is a must have, but no idea if this works well with reactNative ?!
- I usually not use lint-staged as my CI ensure linting, as you want

**Comment by sallesma** [comment]
J'ai ajouté lint-staged et husky pour que prettier et eslint soient lancés à chaque commit

J'ai bougé un peu la config aussi. Maintenant on a de beaux conflits :)

Je vais peut-être résoudre ça de manière un peu barbare

**Review by sallesma — APPROVED** [review]
Looks good to me
Thanks for the hard work, I was too lazy to get to it :)

**Pull request merged**
